name: Publish Release

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.Godot.csproj' -r win-x64  -c Release -o "Godot-${{steps.version.outputs.prop}}"
          7z a -tzip "Godot-${{steps.version.outputs.prop}}.zip" "./Godot-${{steps.version.outputs.prop}}/*"
          rm -r "Godot-${{steps.version.outputs.prop}}"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Godot*"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
